import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import type { PropsWithChildren } from 'react';
import { QueryProvider } from "@/trpc/client";

export default async function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
        <body>
        <QueryProvider>
            {children}
        </QueryProvider>
        </body>
        </html>
    );
}


